#+title: Emacs Config
#+author: Zachary D Meyer
#+PROPERTY: header-args :tangle config.el
#+OPTIONS: toc: 5
#+startup: showeverything

* Table of Contents :toc:
- [[#opening-comments][Opening Comments]]
- [[#themes][Themes]]
- [[#org-mode][Org Mode]]
  - [[#header-size-customization][Header Size Customization]]
  - [[#hide-emphasis-markers][Hide Emphasis Markers]]
  - [[#enable-org-bullets-mode][Enable Org-Bullets-Mode]]
- [[#display-line-numbers-type][Display Line Numbers Type]]
- [[#development-environment][Development Environment]]
  - [[#c-environment][C++ Environment]]
- [[#syntax-highlighting-changes-for-files][Syntax Highlighting Changes For Files]]
  - [[#c][C++]]
- [[#custom-keybinds][Custom Keybinds]]
  - [[#dired-keybinds][Dired Keybinds]]
  - [[#treemacs][Treemacs]]
- [[#documentation-comments][Documentation Comments]]
- [[#org-directory][Org Directory]]
- [[#closing-comments][Closing Comments]]

* Opening Comments
This was here when I first got it.

#+begin_src emacs-lisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

;; Place your private configuration here! Remember, you do not need to run 'doom
;; sync' after modifying this file!


;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets. It is optional.
;; (setq user-full-name "John Doe"
;;       user-mail-address "john@doe.coM")

;; Doom exposes five (optional) variables for controlling fonts in Doom:
;;
;; - `doom-font' -- the primary font to use
;; - `doom-variable-pitch-font' -- a non-monospace font (where applicable)
;; - `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;; - `doom-symbol-font' -- for symbols
;; - `doom-serif-font' -- for the `fixed-pitch-serif' face
;;
;; See 'C-h v doom-font' for documentation and more examples of what they
;; accept. For example:
;;
;;(setq doom-font (font-spec :family "Fira Code" :size 12 :weight 'semi-light)
;;      doom-variable-pitch-font (font-spec :family "Fira Sans" :size 13))
;;
;; If you or Emacs can't find your font, use 'M-x describe-font' to look them
;; up, `M-x eval-region' to execute elisp code, and 'M-x doom/reload-font' to
;; refresh your font settings. If Emacs still can't find your font, it likely
;; wasn't installed correctly. Font issues are rarely Doom issues!

;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:

#+end_src

* Themes
Keep the dark mode theme for now.

#+begin_src emacs-lisp
;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
(setq doom-theme 'doom-one)
#+end_src

* Org Mode
This section contains my org mode tweaks.

** Header Size Customization
Some variety in header sizes.

#+begin_src emacs-lisp
;; Set the font sizes for the org levels.
(custom-set-faces
 '(org-level-1 ((t (:inherit outline-1 :height 1.6))))
 '(org-level-2 ((t (:inherit outline-2 :height 1.3))))
 '(org-level-3 ((t (:inherit outline-3 :height 1.21))))
 '(org-level-4 ((t (:inherit outline-4 :height 1.15))))
 '(org-level-5 ((t (:inherit outline-5 :height 1.09))))
)
#+end_src

** Hide Emphasis Markers
#+begin_src emacs-lisp
(setq org-hide-emphasis-markers t)
#+end_src

** Enable Org-Bullets-Mode
This code will hook org-mode to enable org-bullets-mode.
#+begin_src emacs-lisp
(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
#+end_src

* Display Line Numbers Type
#+begin_src emacs-lisp
;; This determines the style of line numbers in effect. If set to `nil', line
; numbers are disabled. For relative line numbers, set this to `relative'.
(setq display-line-numbers-type 'relative)

#+end_src

* Development Environment
This section outlines the development environment within Emacs.
Currently we only require dap-gdb-lldb.

Only C++ is considered for now.

#+begin_src emacs-lisp
(require 'dap-gdb-lldb)
#+end_src

** C++ Environment
#+begin_src emacs-lisp
;;
;; C++ Development
;;
(with-eval-after-load 'lsp-clangd
  (require 'dap-cpptools)
  (require 'dap-lldb))

#+end_src

* Syntax Highlighting Changes For Files
This section has configuration on specific file types that do not have the
correct syntax highlighting.

** C++
This subsection contains all of the C++ files that need to be in C++ mode.
Currently, it's just the .inl and .tpp files.

#+begin_src emacs-lisp
;;
;; C++ file syntax highlighting
;;
(add-to-list 'auto-mode-alist '(".*\.inl" . cpp-mode))
(add-to-list 'auto-mode-alist '(".*\.tpp" . cpp-mode))
#+end_src

* Custom Keybinds
This section contains my custom keybindings for Doom Emacs.
Some of this stuff has been copied from DistroTube, but I'll make it my own.

** Dired Keybinds
Here are the keybindings for the dired file manager.

|-------------+--------------------+------------------|
| Key Binding | Command            | Description      |
|-------------+--------------------+------------------|
| M-RET       | dired-display-file | Display File     |
| h           | dired-up-directory | Up one directory |
| l           | dired-open-file    | Open file        |
| m           | dired-mark         | Mark file        |
|-------------+--------------------+------------------|


#+begin_src emacs-lisp
;;
;; Dired Keybindings
;;
(map! :leader
      (:prefix ("d" . "dired")
       :desc "Open dired" "d" #'dired
       :desc "Dired jump to current" "j" #'dired-jump)
      (:after dired
        (:map dired-mode-map
         :desc "Peep-dired image previews" "d p" #'peep-dired
         :desc "Dired view file" "d v" #'dired-view-file)))

(evil-define-key 'normal dired-mode-map
  (kbd "M-RET") 'dired-display-file
  (kbd "h") 'dired-up-directory
  (kbd "l") 'dired-open-file
  (kbd "m") 'dired-mark)
#+end_src

** Treemacs
| Key Binding    | Command                   | Description                  |
|----------------+---------------------------+------------------------------|
| <LEADER> z t t | treemacs                  | Open Treemacs                |
| <LEADER> z t a | treemacs-create-file      | Create File                  |
| <LEADER> z t d | treemacs-create-dir       | Create Directory             |
| <LEADER> z t c | treemacs-select-directory | Select Directory in Treemacs |

#+begin_src emacs-lisp
(defun zdmeyer-visit-treemacs() (interactive)
  (funcall 'treemacs)
  (funcall 'treemacs))

(map! :leader (:prefix ("z t" . "Treemacs")
               :desc "Toggle Treemacs" "t" #'treemacs
               :desc "Create File" "a" #'treemacs-create-file
               :desc "Create Directory" "d" #'treemacs-create-dir
               :desc "Change Directory" "c" #'treemacs-select-directory))

#+end_src

* Documentation Comments
This section currently only has code for putting c++ comments for doxygen.

#+begin_src emacs-lisp
;;
;; C Documentatin Comment Style
;;
(setq c-doc-comment-style '((c-mode . gtkdoc)
                            (c++-mode . doxygen)))
#+end_src


* Org Directory
My org directory is just ~/org Use a function stolen online to get every file.

#+begin_src emacs-lisp
;; If you use `org' and don't want your org files in the default location below,
;; change `org-directory'. It must be set before org loads!

(defun sa-find-org-file-recursively (&optional directory filext)
  "Return .org and .org_archive files recursively from DIRECTORY.
If FILEXT is provided, return files with extension FILEXT instead."
  (interactive "DDirectory: ")
  (let* (org-file-list
         (case-fold-search t)         ; filesystems are case sensitive
         (file-name-regex "^[^.#].*") ; exclude dot, autosave, and backupfiles
         (filext (or filext "org$\\\|org_archive"))
         (fileregex (format "%s\\.\\(%s$\\)" file-name-regex filext))
         (cur-dir-list (directory-files directory t file-name-regex)))
    ;; loop over directory listing
    (dolist (file-or-dir cur-dir-list org-file-list) ; returns org-file-list
      (cond
       ((file-regular-p file-or-dir)             ; regular files
        (if (string-match fileregex file-or-dir) ; org files
            (add-to-list 'org-file-list file-or-dir)))
       ((file-directory-p file-or-dir)
        (dolist (org-file (sa-find-org-file-recursively file-or-dir filext)
                          org-file-list) ; add files found to result
          (add-to-list 'org-file-list org-file)))))))

(setq org-directory "~/org/")
(setq org-agenda-files (append (sa-find-org-file-recursively "~/org/")))

#+end_src

* Closing Comments
Preserve this crap.

#+begin_src emacs-lisp
;; Whenever you reconfigure a package, make sure to wrap your config in an
;; `after!' block, otherwise Doom's defaults may override your settings. E.g.
;;
;;   (after! PACKAGE
;;     (setq x y))
;;
;; The exceptions to this rule:
;;
;;   - Setting file/directory variables (like `org-directory')
;;   - Setting variables which explicitly tell you to set them before their
;;     package is loaded (see 'C-h v VARIABLE' to look up their documentation).
;;   - Setting doom variables (which start with 'doom-' or '+').
;;
;; Here are some additional functions/macros that will help you configure Doom.
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;; Alternatively, use `C-h o' to look up a symbol (functions, variables, faces,
;; etc).
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.

#+end_src
